steps:

# - id: "Realizando docker-compose up"
#   name: 'docker/compose'
#   args: ['up', '-d']



- id: Run test
  name: "gcr.io/cloud-builders/go"
  args: ["test","./src"]
  env: ["GOPATH=."]

- id: Run the program
  name: "gcr.io/cloud-builders/go"
  args: ["run", "./src"]
  env: ["GOPATH=."]

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio-ci:1.0.0'
  - '.'

- id: Test Image
  name: 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  args: ["version"]
  env: ["GOPATH=."]
  # args: ["go", "run", "main.go"]  
  # # env: ["GOPATH=."]

images:
  - 'gcr.io/$PROJECT_ID/desafio-ci:latest'
  - 'gcr.io/$PROJECT_ID/desafio-ci:1.0.0'