steps:

# - id: "Realizando docker-compose up"
#   name: 'docker/compose'
#   args: ['up', '-d']

- id: Run test
  name: "gcr.io/cloud-builders/go"
  args: ["test","./src"]
  env: ["GOPATH=."]

- id: Run the program
  name: "gcr.io/cloud-builders/go"
  args: ["run", "./src"]
  env: ["GOPATH=."]

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio:latest'
  - '-t'
  - 'gcr.io/$PROJECT_ID/desafio:1.0.0'
  - '.'
- name: 'gcr.io/$PROJECT_ID/desafio'
  args: ['version']
images:
  - 'gcr.io/$PROJECT_ID/desafio:latest'
  - 'gcr.io/$PROJECT_ID/desafio:1.0.0'