steps:
- id: Run test
  name: "gcr.io/cloud-builders/go"
  args: ["test","./src"]
  env: ["GOPATH=."]

- id: Run the program
  name: "gcr.io/cloud-builders/go"
  args: ["run", "./src"]
  env: ["GOPATH=."]

